# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to Telekom

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node Packages
        uses: actions/setup-node@v3
        with:
          node-version: 18.4
          cache: "npm"
      - run: npm ci --legacy-peer-deps --prefer-offline --no-audit --progress=false --registry https://registry.npmjs.org
      - run: npm run build

      - name: SSH Clean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TELEKOM_HOST }}
          username: ${{ secrets.TELEKOM_USER }}
          password: ${{ secrets.TELEKOM_PASS }}
          port: ${{ secrets.TELEKOM_PORT }}
          script: |
            shopt -s extglob
            rm -r /home/www/public_html/!(api.php) || true

      - name: SSH Copy
        uses: youxingz/sshpass-scp-action@v3
        if: always()
        timeout-minutes: 10
        with:
          host: ${{ secrets.TELEKOM_HOST }}
          user: ${{ secrets.TELEKOM_USER }}
          pass: ${{ secrets.TELEKOM_PASS }}
          dist: /home/www/public_html
          src: public/*


