# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish to Telekom

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.4
      uses: actions/setup-node@v3
      with:
        node-version: 18.4
        cache: "npm"
    - run: npm i --legacy-peer-deps --prefer-offline --no-audit --progress=false
    - run: npm run build
    - run: ls -a

  upload:

    runs-on: ubuntu-latest

    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: SSHPASS
      uses: youxingz/sshpass-scp-action@v3
      with:
        node-version: 18.x
        cache: 'npm'
        host: ${{ secrets.TELEKOM_HOST }}
        username: ${{ secrets.TELEKOM_AUTH }}
        password: ${{ secrets.TELEKOM_PASS }}
        dist: /home/www/pablo
        src: public
